import { useEffect, useState } from 'react';
import { CreditCard, CheckCircle, AlertCircle, ExternalLink, FileText, X, Clock, Download } from 'lucide-react';
import hstApi from '../../api/hstAxios';
import toast from 'react-hot-toast';
import { PageLoader } from '../../components/Spinner';

async function downloadReceipt(billId, month, year) {
  try {
    const MONTHS_FULL = ['January','February','March','April','May','June','July','August','September','October','November','December'];
    const res = await hstApi.get(`/residents/me/receipt/${billId}`, { responseType: 'blob' });
    const url = URL.createObjectURL(res.data);
    const a = document.createElement('a');
    a.href = url;
    a.download = `rent-receipt-${MONTHS_FULL[(month ?? 1) - 1]}-${year}.pdf`;
    a.click();
    URL.revokeObjectURL(url);
  } catch {
    toast.error('Download failed');
  }
}

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export default function ResidentBills() {
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [receiptBill, setReceiptBill] = useState(null);

  useEffect(() => {
    hstApi.get('/billing/my')
      .then(r => setBills(r.data.bills))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <PageLoader />;

  const unpaid  = bills.filter(b => !b.isPaid);
  const partial = bills.filter(b => !b.isPaid && b.paidComponents && (b.paidComponents.rent || b.paidComponents.electricity || b.paidComponents.food));
  const paid    = bills.filter(b => b.isPaid);

  return (
    <div className="p-5 md:p-8 space-y-6 animate-fade-up">
      <div>
        <h1 className="text-2xl font-bold text-slate-800">My Bills</h1>
        <p className="text-slate-500 text-sm mt-0.5">
          {unpaid.length > 0
            ? <span className="text-red-500 font-medium">{unpaid.length} unpaid bill{unpaid.length > 1 ? 's' : ''}</span>
            : <span className="text-emerald-600 font-medium">All bills paid ✓</span>
          }
        </p>
      </div>

      {unpaid.length > 0 && (
        <section>
          <h2 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Pending</h2>
          <div className="space-y-3">
            {unpaid.map(b => <BillCard key={b._id} b={b} onViewReceipt={() => setReceiptBill(b)} />)}
          </div>
        </section>
      )}

      {paid.length > 0 && (
        <section>
          <h2 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Paid</h2>
          <div className="space-y-3">
            {paid.map(b => <BillCard key={b._id} b={b} onViewReceipt={() => setReceiptBill(b)} />)}
          </div>
        </section>
      )}

      {bills.length === 0 && (
        <div className="text-center py-16 text-slate-400">
          <CreditCard size={40} className="mx-auto mb-3 opacity-30" />
          <p className="font-medium">No bills yet.</p>
          <p className="text-sm mt-1">Bills will appear here once generated by admin.</p>
        </div>
      )}

      {receiptBill && (
        <ReceiptModal bill={receiptBill} onClose={() => setReceiptBill(null)} />
      )}
    </div>
  );
}

// ── Bill Card ────────────────────────────────────────────────────────────────
function BillCard({ b, onViewReceipt }) {
  const pc = b.paidComponents ?? { rent: false, electricity: false, food: false };
  const isPartial = !b.isPaid && (pc.rent || pc.electricity || pc.food);
  const remaining = b.total - (b.paidAmount ?? 0);

  return (
    <div className={`bg-white rounded-2xl border shadow-sm p-5 ${
      b.isPaid ? 'border-slate-100' : isPartial ? 'border-amber-100' : 'border-red-100'
    }`}>
      {/* Header row */}
      <div className="flex items-start justify-between mb-4">
        <div>
          <h3 className="font-bold text-slate-800 text-lg">{MONTHS[(b.month ?? 1) - 1]} {b.year}</h3>
          <p className="text-xs text-slate-400 mt-0.5">
            Receipt No: HST-{b._id.slice(-8).toUpperCase()}
          </p>
        </div>
        {b.isPaid ? (
          <span className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-full bg-emerald-100 text-emerald-700">
            <CheckCircle size={12} /> Paid
          </span>
        ) : isPartial ? (
          <span className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-full bg-amber-100 text-amber-700">
            <Clock size={12} /> Partial
          </span>
        ) : (
          <span className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-full bg-red-100 text-red-600">
            <AlertCircle size={12} /> Unpaid
          </span>
        )}
      </div>

      {/* Component breakdown */}
      <div className="space-y-2 mb-4">
        {b.rent > 0 && (
          <ComponentRow
            label="Rent"
            amount={b.rent}
            paid={b.isPaid || pc.rent}
            color="indigo"
          />
        )}
        {b.electricityShare > 0 && (
          <ComponentRow
            label="Electricity (EB)"
            amount={b.electricityShare}
            paid={b.isPaid || pc.electricity}
            color="yellow"
          />
        )}
        {b.foodTotal > 0 && (
          <ComponentRow
            label="Food"
            amount={b.foodTotal}
            paid={b.isPaid || pc.food}
            color="emerald"
          />
        )}

        <div className="border-t border-slate-100 pt-2 flex items-center justify-between">
          <span className="text-sm font-bold text-slate-700">Total</span>
          <span className="text-base font-bold text-slate-900">₹{b.total}</span>
        </div>

        {isPartial && (
          <>
            <div className="flex items-center justify-between text-sm">
              <span className="text-slate-500">Paid so far</span>
              <span className="font-semibold text-emerald-700">₹{b.paidAmount ?? 0}</span>
            </div>
            <div className="flex items-center justify-between text-sm">
              <span className="text-slate-500">Remaining</span>
              <span className="font-bold text-red-600">₹{remaining}</span>
            </div>
          </>
        )}
      </div>

      {/* Paid date */}
      {b.isPaid && b.paidAt && (
        <p className="text-xs text-slate-400 mb-3">
          Paid on {new Date(b.paidAt).toLocaleDateString('en-IN', { dateStyle: 'medium' })}
        </p>
      )}

      {/* Actions */}
      <div className="flex gap-2 flex-wrap">
        <button
          onClick={onViewReceipt}
          className="flex items-center gap-1.5 border border-slate-200 text-slate-600 hover:bg-slate-50 text-xs font-semibold px-3 py-2 rounded-xl transition-colors">
          <FileText size={13} /> View Receipt
        </button>

        {b.isPaid && (
          <button
            onClick={() => downloadReceipt(b._id, b.month, b.year)}
            className="flex items-center gap-1.5 border border-indigo-200 text-indigo-600 hover:bg-indigo-50 text-xs font-semibold px-3 py-2 rounded-xl transition-colors">
            <Download size={13} /> Download PDF
          </button>
        )}

        {!b.isPaid && b.paymentLink && (
          <a href={b.paymentLink} target="_blank" rel="noopener noreferrer"
            className="flex items-center gap-1.5 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold px-3 py-2 rounded-xl transition-colors shadow-md shadow-indigo-100 active:scale-[0.97]">
            <ExternalLink size={13} />
            {isPartial ? `Pay Remaining ₹${remaining}` : `Pay Now ₹${b.total}`}
          </a>
        )}
      </div>
    </div>
  );
}

// ── Component Row ────────────────────────────────────────────────────────────
function ComponentRow({ label, amount, paid, color }) {
  const colors = {
    indigo:  { bg: 'bg-indigo-50',  text: 'text-indigo-700',  badge: 'bg-indigo-100' },
    yellow:  { bg: 'bg-yellow-50',  text: 'text-yellow-700',  badge: 'bg-yellow-100' },
    emerald: { bg: 'bg-emerald-50', text: 'text-emerald-700', badge: 'bg-emerald-100' },
  };
  const c = colors[color];

  return (
    <div className={`flex items-center justify-between rounded-xl px-3 py-2.5 ${c.bg}`}>
      <div className="flex items-center gap-2">
        <span className={`text-sm font-medium ${c.text}`}>{label}</span>
        {paid && (
          <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded-full ${c.badge} ${c.text}`}>
            PAID
          </span>
        )}
      </div>
      <span className={`text-sm font-bold ${c.text}`}>₹{amount}</span>
    </div>
  );
}

// ── Receipt Modal ────────────────────────────────────────────────────────────
function ReceiptModal({ bill: b, onClose }) {
  const pc = b.paidComponents ?? { rent: false, electricity: false, food: false };
  const isPartial = !b.isPaid && (pc.rent || pc.electricity || pc.food);
  const receiptNo = `HST-${b._id.slice(-8).toUpperCase()}`;
  const remaining = b.total - (b.paidAmount ?? 0);

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
      onClick={onClose}>
      <div className="bg-white rounded-2xl w-full max-w-sm shadow-2xl overflow-hidden"
        onClick={e => e.stopPropagation()}>

        {/* Receipt header */}
        <div className="bg-indigo-600 px-6 py-5 text-white relative">
          <button onClick={onClose}
            className="absolute top-3 right-3 p-1.5 rounded-lg bg-white/20 hover:bg-white/30 transition-colors">
            <X size={14} />
          </button>
          <p className="text-xs font-semibold uppercase tracking-widest text-indigo-200 mb-1">Hostel Receipt</p>
          <p className="text-xl font-bold">{MONTHS[(b.month ?? 1) - 1]} {b.year}</p>
          <p className="text-xs text-indigo-300 mt-1">{receiptNo}</p>

          {/* Status pill */}
          <div className="mt-3">
            {b.isPaid ? (
              <span className="inline-flex items-center gap-1.5 bg-white/20 text-white text-xs font-bold px-3 py-1.5 rounded-full">
                <CheckCircle size={12} /> Fully Paid
              </span>
            ) : isPartial ? (
              <span className="inline-flex items-center gap-1.5 bg-amber-400/30 text-amber-100 text-xs font-bold px-3 py-1.5 rounded-full">
                <Clock size={12} /> Partially Paid
              </span>
            ) : (
              <span className="inline-flex items-center gap-1.5 bg-red-400/30 text-red-100 text-xs font-bold px-3 py-1.5 rounded-full">
                <AlertCircle size={12} /> Unpaid
              </span>
            )}
          </div>
        </div>

        {/* Line items */}
        <div className="p-5 space-y-2">
          <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Breakdown</p>

          {b.rent > 0 && (
            <ReceiptLine label="Monthly Rent" amount={b.rent} paid={b.isPaid || pc.rent} />
          )}
          {b.electricityShare > 0 && (
            <ReceiptLine label="Electricity (EB)" amount={b.electricityShare} paid={b.isPaid || pc.electricity} />
          )}
          {b.foodTotal > 0 && (
            <ReceiptLine label="Food (meal bookings)" amount={b.foodTotal} paid={b.isPaid || pc.food} />
          )}

          <div className="border-t border-slate-200 pt-3 mt-1 flex items-center justify-between">
            <span className="font-bold text-slate-800">Total</span>
            <span className="text-lg font-bold text-slate-900">₹{b.total}</span>
          </div>

          {isPartial && (
            <div className="bg-amber-50 border border-amber-100 rounded-xl px-4 py-3 space-y-1.5 mt-2">
              <div className="flex justify-between text-sm">
                <span className="text-slate-600">Paid so far</span>
                <span className="font-bold text-emerald-700">₹{b.paidAmount ?? 0}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-slate-600 font-semibold">Balance due</span>
                <span className="font-bold text-red-600">₹{remaining}</span>
              </div>
            </div>
          )}

          {b.isPaid && b.paidAt && (
            <p className="text-xs text-slate-400 text-center pt-1">
              Paid on {new Date(b.paidAt).toLocaleDateString('en-IN', { dateStyle: 'long' })}
            </p>
          )}
        </div>

        {/* Footer actions */}
        <div className="px-5 pb-5 space-y-2">
          {!b.isPaid && b.paymentLink && (
            <a href={b.paymentLink} target="_blank" rel="noopener noreferrer"
              className="flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white py-3 rounded-xl text-sm font-semibold transition-all shadow-lg shadow-indigo-200 active:scale-[0.97] w-full">
              <ExternalLink size={15} />
              {isPartial ? `Pay Remaining ₹${remaining}` : `Pay Now ₹${b.total}`}
            </a>
          )}
          {b.isPaid && (
            <button onClick={() => downloadReceipt(b._id, b.month, b.year)}
              className="flex items-center justify-center gap-2 w-full py-2.5 bg-indigo-50 border border-indigo-200 text-indigo-700 rounded-xl text-sm font-semibold hover:bg-indigo-100 transition-colors">
              <Download size={15} /> Download PDF Receipt
            </button>
          )}
          <button onClick={onClose}
            className="w-full py-2.5 border border-slate-200 rounded-xl text-sm font-medium text-slate-500 hover:bg-slate-50 transition-colors">
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

function ReceiptLine({ label, amount, paid }) {
  return (
    <div className="flex items-center justify-between py-2 border-b border-slate-50">
      <div className="flex items-center gap-2">
        <span className="text-sm text-slate-700">{label}</span>
        {paid && (
          <span className="text-[10px] font-bold bg-emerald-100 text-emerald-700 px-1.5 py-0.5 rounded-full">PAID</span>
        )}
      </div>
      <span className="text-sm font-semibold text-slate-800">₹{amount}</span>
    </div>
  );
}
